name: ghtopdep
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - selectolax
    - tabulate
    - click
    - halo
    - cachecontrol
    - lockfile
    - requests
    - github3.py
    - appdirs
    - pipdate
    - better_exceptions
    - pysnooper
    - pytest
    - flake8
